siteTitle="Smooch Docs"
linkPrefix = "/"

[sections.docs]
subsections = [
    'home',
    'programmable-messaging',
    'users'
]


[subsections.home]
name = "Home"
pages = [
    "/docs/",
    "/docs/api-quickstart/",
    "/docs/business-quickstart/"
]


[subsections.programmable-messaging]
name = "Programmable Messaging"
pages = [
    "/docs/authenticating-to-smooch-api/",
    "/docs/sending-and-receiving-messages/"
]


[subsections.users]
name = "Users"
pages = [
    "/docs/creating-users/",
    "/docs/authenticating-users/",
    "/docs/managing-user-information/",
    "/docs/linking-users-to-sms/"
]

[subsections.api]
name = "API Reference"
pages = [
    "/api/",
    "/api/connect/",
    "/api/inside/"
]
